name: CD
on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.APP_PASS }}
      node-version: 16

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
          
      - name: deploy
        run: 
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd ventalis_intranet &&
          git pull &&
          php composer.phar install &&
          php bin/console d:m:m -n"